### ISSUE TITLE
Mongo Driver

### ISSUE THREAD

**Issue by timscully1983** [3drepo/3drepobouncer#1]
- Investigate connection pooling
- Investigate authentication method (changed from MONGO-CR)
- Functions: only required by RepoBSON

**Comment by carmenfan** [comment]
(mostly info for my own purpose)
Investigate connection pooling - not supported, we need to implement our own pooling mechanism.
Investigate authentication method (changed from MONGO-CR) - it now uses [SCRAM-SHA-1](http://docs.mongodb.org/manual/core/authentication/#authentication-scram-sha-1)

**Comment by carmenfan** [comment]
Considering all basic features supported. Any new bugs/features should be a new issue from this point.
