### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by shongololo** [3drepo/3drepobouncer#128]
I am getting an error when trying to build 3drepobouncer:

The error refers to `boost/property_tree/detail/json_parser/read.hpp` which doesn't exist, is this perhaps a typo? Because `boost/property_tree/detail/json_parser_read.hpp` does exist.

Here is the full output:
```
[ 51%] Building CXX object bouncer/CMakeFiles/3drepobouncer.dir/src/repo/lib/repo_property_tree.cpp.o

In file included from /home/user_home/3drepobouncer/bouncer/src/repo/lib/repo_property_tree.h:24:0,
                 from /home/user_home/3drepobouncer/bouncer/src/repo/lib/repo_property_tree.cpp:18:

/home/user_home/3drepobouncer/bouncer/src/repo/lib/json_parser.h:17:59: fatal error: 

boost/property_tree/detail/json_parse

r/read.hpp: No such file or directory

 #include <boost/property_tree/detail/json_parser/read.hpp>
                                                           ^
compilation terminated.
make[2]: *** [bouncer/CMakeFiles/3drepobouncer.dir/src/repo/lib/repo_property_tree.cpp.o] Error 1
make[1]: *** [bouncer/CMakeFiles/3drepobouncer.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by jozefdobos** [comment]
There were recent changes in Boost library so you're very likely using a wrong version number. 

@carmenfan I recall we had similar issues before...

**Comment by carmenfan** [comment]
Shouldn't be a problem, I did a fix for that, our dev server is using 1.60 and it's fine.

What version  of boost are you using? we only support versions beyond 1.55

**Comment by shongololo** [comment]
@carmenfan that'll be it, I'll upgrade. Thanks.

**Comment by shongololo** [comment]
I'm trying again with boost version 1.61 and seem to be running into the same issue again.

**Comment by carmenfan** [comment]
Ok the boost guys moved the files again in 1.61.... 

I've modified the code to address this. If you pull the lastest changes from master it should compile fine. (It works in windows at least..)

Let me know if you have further problems!

**Comment by shongololo** [comment]
@carmenfan thanks, using the latest master I'm now able to get to the end stage of make except that it is now throwing this error:
```
../bouncer/lib3drepobouncer.so: undefined reference to `boost::log::v2_mt_posix::aux::code_convert_impl(wchar_t const*, unsigned long, std::string&, std::locale const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [client/3drepobouncerClient] Error 1
make[1]: *** [client/CMakeFiles/3drepobouncerClient.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by carmenfan** [comment]
@thenrikie  @timscully1983  have you guys came across this? I'll try to spin up a vm with Ubuntu 14.04 and see if i can replicate it

**Comment by carmenfan** [comment]
@shongololo  I'm struggling to replicate the problem. My Ubuntu Trusty VM managed to build this fine.  (gcc 4.9, boost 1.61)

That error is suggesting that the compiler failed to find the boost log dynamic library. Can you see if can locate it in your filesystem? You should see the followings if you ls into your boost library folder

![image](https://cloud.githubusercontent.com/assets/11945337/16150787/3e15a93c-3491-11e6-86f7-b80298c0c10e.png)


I built boost from scratch (since a quick google wasn't showing any prebuilt binaryes for 1.61) and the following command was used:

````
	./bootstrap.sh --with-libraries=atomic,system,thread,chrono,log,filesystem,program_options,regex
	./b2 install
````

**Comment by shongololo** [comment]
@carmenfan thanks. The libboost log related files do seem to be there but I tried recompiling boost in case (using the flags) though still seem to come unstuck. I'll give this a try on a fresh VM in case that works better.

Error msg:
```
Linking CXX executable 3drepobouncerClient
../bouncer/lib3drepobouncer.so: undefined reference to `boost::log::v2_mt_posix::aux::code_convert_impl(wchar_t const*, unsigned long, std::st
ring&, std::locale const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [client/3drepobouncerClient] Error 1
make[1]: *** [client/CMakeFiles/3drepobouncerClient.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by carmenfan** [comment]
@shongololo  try setting the boost library dir and rerun cmake (delete your build directory to avoid any caching, just in case):

````
export BOOST_LIBRARYDIR=directory_to_your_boost_libs
````

**Comment by shongololo** [comment]
@carmenfan thanks, turning off the command line interface did the trick for now.
