### ISSUE TITLE
Update User BSON to understand licensing information

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#134]
In anticipation of the ability to manipulate licensing information on the GUI

**Comment by carmenfan** [comment]
Inactive User bson:
![image](https://cloud.githubusercontent.com/assets/11945337/17146150/375ca1e4-5355-11e6-9738-b8473d6a5247.png)

Standard User account:
![image](https://cloud.githubusercontent.com/assets/11945337/17146183/5d6d2e62-5355-11e6-8138-c19bdf0837ed.png)

Paid user account:
![image](https://cloud.githubusercontent.com/assets/11945337/17146302/d2f5f722-5355-11e6-94fc-254f8e1ae46f.png)

Billing info:
![image](https://cloud.githubusercontent.com/assets/11945337/17146332/f434bfa4-5355-11e6-9958-a2335ae40bc4.png)

**Comment by thenrikie** [comment]
full schema can be found here https://github.com/3drepo/3drepo.io/blob/staging/backend/models/user.js

**Comment by carmenfan** [comment]
seems to be working. Merged to branch v1.3
