### ISSUE TITLE
Warning: Comparison of constant 16 with expression of type bool is always true

### ISSUE THREAD

**Issue by y-fedorov** [3drepo/3drepobouncer#154]
3drepobouncer-1.2.0/bouncer/src/repo/core/model/repo_node_utils.h:415:33: Comparison of constant 16 with expression of type 'bool' is always true

Version: 1.2.0, also available in master. 

![screen shot 2016-10-19 at 08 38 40](https://cloud.githubusercontent.com/assets/1410982/19506876/c186443c-95d7-11e6-81f3-160c0b27282a.png)

```
$ xcodebuild -version
Xcode 8.0
Build version 8A218a
```

```
$ clang --version
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by carmenfan** [comment]
That's a very odd condition... Not sure what I was thinking when i wrote that... ;)


We'll fix it on the next release, thanks for spotting it!

**Comment by carmenfan** [comment]
fixed and now in master

**Comment by y-fedorov** [comment]
Thank you
