### ISSUE TITLE
Default visibility should be stored in Mesh node, not generated at selection tree

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#173]
This way, the utility creating the mesh node determines whether the mesh node should be visible by default or not, not the selection tree maker.

This will make it a lot easier to hide meshes on the gui (which currently does not read the selection tree) and also better integration when we add more hidden by default geometry

**Comment by timscully1983** [comment]
@carmenfan  Why can't this work with modelProperties ? Rather than bloating the tree.

**Comment by carmenfan** [comment]
It is stored in model properties? It's generated within the selection tree maker, which generates model properties. I can't remember if it is in the tree or not, if it is, it's because pinakin needed it to set the default look on the tree... i think. We can by all means remove that if it is not needed.

The concern here is that currently it's a bit hackery, whether something should be hidden by default is determined by whether the name of the mesh contains `(IFC Space)` in the name. If we actually add a flag on the mesh node then we would just be checking this flag on the mesh node when we generate the tree/modelproperties, which should be flagged by IFC importer, and anythign in the future which we might want to hide by default

**Comment by timscully1983** [comment]
Ok, I see now. It was once in the tree but I think we decided it was too slow to read everything through. However, not sure how it applies to making it easier to hide in the GUI vs modelProperties.

Anyway, as this is an optimization to a project that is being replaced, I say just leave it and I'll close it.
