### ISSUE TITLE
RepoBSON

### ISSUE THREAD

**Issue by timscully1983** [3drepo/3drepobouncer#2]
- Container with key/value pairs
- Notion of revision/scene graph pointer to RepoBSON
- Base on BSON online (now been separated from Mongo)
- Provide setter/getter functions
   - Recreate immutable BSON
   - Notify revision/scene graph of change
- Function to load/commit to database
- Remember to use upsert. Parent must update UID. If UID doesn't exist it's an insert, if it does it's an update.

**Comment by carmenfan** [comment]
RepoBSON is really just a dumb interface to MongoBSON, this inheritance to MongoBSON should be removed eventually and use a generic BSON library.

Query constructions is handled by database handlers (see ISSUE #1) 

Notion of Parents and any other semantic meaning on the fields should be imposed on RepoNode (see ISSUE #3 ), as special cases such as User documents would not have a notion of parent.

I'd consider this ISSUE resolved. Only possible addition may be a setter, but the whole notion of setter may be better described on RepoNode (even if we allow setters)
