### ISSUE TITLE
cmake can't find Mongo if using mongodb-org

### ISSUE THREAD

**Issue by fazelmk** [3drepo/3drepobouncer#217]
I'm using ubuntu 14.04 and cmake script can't find Mongo if I use mongodb-org installation.
It finds Mongo if I install mongodb but it's an old version and give me this error
```
error: ‘class mongo::DBClientBase’ has no member named ‘isStillConnected’
   if (!worker->isStillConnected())
```

How do I proceed?

**Comment by carmenfan** [comment]
Hi,

Installing mongodb server will not help as this library requires the legacy c++ client driver, which can be found here: https://github.com/mongodb/mongo-cxx-driver/tree/legacy

**Comment by fazelmk** [comment]
the legacy driver don't compile here.

```
src/mongo/util/assert_util.h:231:28: error: nonnull argument 'this' compared to NULL [-Werror=nonnull-compare]
         if (MONGO_unlikely(!(expr))) {
```

mongo --version
MongoDB shell version: 2.4.9

scons --version
SCons by Steven Knight et al.:
	script: v2.3.0, 2013/03/03 09:48:35, by garyo on reepicheep
	engine: v2.3.0, 2013/03/03 09:48:35, by garyo on reepicheep
	engine path: ['/usr/lib/scons/SCons']

g++ (Ubuntu 7.2.0-1ubuntu1~14.04) 7.2.0
gcc (Ubuntu 7.2.0-1ubuntu1~14.04) 7.2.0


any ideia why?

**Comment by carmenfan** [comment]
It's probably best if you ask the mongo guys as we don't own the software. Though it seems like you are using some pretty cutting edge GCC version and i'm not sure how well they support that. (we've only ever built our tools with GCC 4.9-5.x ourselves)

**Comment by carmenfan** [comment]
Also your mongo is very outdated - you should upgrade it to at least 3.0. But that shouldn't be relevant to you compiling the driver.

**Comment by fazelmk** [comment]
will downgrade gcc and g++ se if I get any luck.. tanks for the help

**Comment by carmenfan** [comment]
Closing this as it doesn't sound like you are having trouble with 3drepobouncer itself. Feel free to reply again if  you run into any further issue!
