### ISSUE TITLE
Texture support in BIM files

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#391]
#### Preparation
- [x] Get access to some 3D models with textures
- [x] Compile and run the the test program from (Program.cs) the [related ](https://github.com/3drepo/3drepoPlugin/pull/131)branch to get the resultant BIM file
- [x] Examine C# code to understand the BIM format layout 
- [x] *SHOULD*: Create  description/diagram of the BIM format
> See the Notes section below
- [x] Highlight changed areas in the BIM format to allow for textures 
- [x] Pass feedback on for internal inconsistencies in the .NET code for the latest BIM003 format

#### Bouncer dev
- [ ] Complete the notes on getting bouncer dev environment up [here](https://github.com/3drepo/3drepobouncer/issues/396)
- [x] Highlight the key areas that require updating to match the changes in the format
- [x] Write a test to pass on processing the BIM003 file
- [x] Implement code changes
- [x] Probe for texture notes and attempt to binary dump texture to an image file
- [x] Write tests for BIM001/002
- [x] Write edge case tests for the above  
- [x] Write system test for the client exe
- [x] Set up the local environment for converting to unity asset bundles
- [x] Test with large BIM files (via client)
- [x] SHOULD: Export to Asset bundle

### Assumptions
- Changes will be backwards compatibility with v2/1 of the BIM format.

### Questions
- What is sizes for? If its the size of each node, then sizes[0] does make sense...
> Updated format descriptions with correct info about this
- I cannot find a BIM001 label/property in the git history for the exporter was it ever publicly released?
> This is in the format descriptions below
- Can we place small 3d models used for unit testing the .NET code [here](https://github.com/3drepo/tests)?
> Can use the linked repo 

### Observations going through this issue

- metadata is duplicated in the current BIM format. This also complicates importing of the model in bouncer

### Related ticket
see https://github.com/3drepo/3drepoPlugin/issues/105

### Reference 

[Wiki](https://github.com/3drepo/wiki/wiki/BIM-file-format-descriptions) page for the file format descriptions

**Comment by har00n-haider** [comment]
Observations going through this issue:

- metadata is duplicated in the current BIM format. This also complicates importing of the model in bouncer

**Comment by har00n-haider** [comment]
@carmenfan , I'm getting close to testing the solution with with the BIM003 file generated by the plugins. Could you point me to some BIM001/BIM002 files I can use for unit testing?

**Comment by har00n-haider** [comment]
@carmenfan Is there reason that we are down casting to float [here](https://github.com/3drepo/3drepobouncer/blob/68f598249130567dad0bf585306a8ca76a76883b/bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_3drepo.cpp#L528), even though we may have 64bit verts? I noticed that there was no makeMeshNode for 64bit verts are they not supported?

**Comment by carmenfan** [comment]
> @carmenfan Is there reason that we are casting to float [here](https://github.com/3drepo/3drepobouncer/blob/68f598249130567dad0bf585306a8ca76a76883b/bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_3drepo.cpp#L528), even though we may have 64bit verts? I noticed that there was no makeMeshNode for 64bit verts are they not supported?

Every single renderer in the world seems to work on 32bit vertices so there's no point storing them in 64 bit (would double the memory usage and we'd have to end up casting it down before sending it to the renderer), so we store it in 32bit.

However, a lot of CAD software works in crazy values (like 1e6-1e7) due to the fact that they work in some form of world coordinate system, so they need 64bit representation at import to preserve the precision. 

Luckily they don't use the whole scale of the number range. So we calculate the world offset (minimum point within the model) and subtract that off every single vertices. This way the numbers become significantly smaller to the point we can preserve the precision using 32bit values. So this is what is going on on that line.

**Comment by carmenfan** [comment]
> @carmenfan , I'm getting close to testing the solution with with the BIM003 file generated by the plugins. Could you point me to some BIM001/BIM002 files I can use for unit testing?

I thought we had some system test setup for .bim but it looks like I was imagining things.. 😆 

If you install the current release version of the plugin you should be able create BIM002:
https://www.dropbox.com/s/co35ehx75pewsxw/%5B4.6.1%5D%203D%20Repo%20Navisworks%20Plugins.msi?dl=0

this is 2.8.0, which should produce  BIM001: https://www.dropbox.com/s/gghy33rnsh7yela/%5Bv2.8%5D%203D%20Repo%20Navisworks%20Plugins.msi?dl=0

Make sure the files are relatively small (like a cube or something) so Travis doesn't take forever.

While you're at it, if you create some system test as well (can use the same model files, that's fine), that would be great too (in st_3drepobouncerClient.cpp)
