### ISSUE TITLE
WIP: Create a wiki entry on setting up the environment to develop and test bouncer

### ISSUE THREAD

**Issue by har00n-haider** [3drepo/3drepobouncer#396]
Current notes below

### 1. Getting the server running
- [Download](https://www.mongodb.com/try/download/community) MongoDb server v3.4. You may want to add this to your path
- **Optional** Download Robo 3T to visualize the database
- Clone the [test repository ](https://github.com/3drepo/tests), this contains the test database and 3d models required for unit & system tests to run
- Default login for the standard server is:
   - **database name**: admin
   - **username**: testUser
   - **password**: 3drepotest
   - **localhost** port: 27017
- Run the server in a console with the command mongod --dbpath <instert path>
- 

### Visualising the database with Robot 3T

- Use the credentials mentioned in the server setup

### Running the unit testing loop

- Make sure the mongodb is running
- Restore the database to git checked out dump (from the test git repot)
- Run the unit tests

### Running the unit test executable
- The standard build flow will not put all the binary dependencies into the test exe output folder so you will need to set up path variables in order to have the exe link to the its respective DLLS. Two main options to do this
    - Create a script that sets up the path variables, and then runs the test exe
    - Add the variables to the 

### Building the bouncer

- Need to use the argument "-Tv140" for the MS C++ 140 platform tools set 
- Can use set option "-D" for turning on things like the test project build
- Use the GUI to make sure you know what is going on between the configure and build stages

### Observed Issues

- INSTALL fails for me on the setlocal command
^ There should be PREFIX appended to the environment variable required for google test to fix this 

---- PART 2---
requirements:
nodejs v 10.x: https://nodejs.org/dist/latest-v10.x/
yarn; https://yarnpkg.com/lang/en/docs/install/
rabbitmq server:
UnityEditor 2019.3* (or 2019.4 if 2019.3 is not available anymore) along with WebGL support
cloned repos (bouncer.io and 3drepounity)
built and installed bouncer, along with any PATH requirements

front end
- yarn install 
- yarn build

backend (requires no building)

make a copy of the config.js (used by the backend)
Update the config.js for local use (insert example here)

Run mongodb

Create a user in Robot3T (to confirm the connection)
Add the created login to the config for the back end

Make sure that rabbit mq is installed and running

amend the bouncer worker config file for local use
** insert commented json here**

build the bouncer wrapper project (in unity) (via the CMAKE utility)
make sure the environment variables exist for this solution

unity repo codebase needs to be in roughly in sync with the bouncer codebase (commit wise)

PATHS need to be setup for the unity editor do find the dlls (**insert required PATH variables  here**)
^edit the batch file for this step?

**Comment by carmenfan** [comment]
@har00n-haider 
![image](https://user-images.githubusercontent.com/11945337/98528378-1b081f80-2274-11eb-9ec3-d942ffd4fe36.png)
Did you change the prefix? if not then that'd be because you're trying to install to programfiles without running it with admin privileges.

**Comment by har00n-haider** [comment]
This has been completed [here](https://github.com/3drepo/wiki/wiki/3drepo.io-Setting-up-a-local-instance-for-development). Closing the ticket.
