### ISSUE TITLE
Synchro 6.3 support

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepobouncer#439]
### Description

When uploading the file "MO_SPM from 6_3_1_2 .spm" (created in Synchro 6.3.1.2) from the Gammon support folder ([Dropbox Link](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Clients/Customers/Gammon/Support/210223/Models/SPM)) the 3D Repo UI returns the message:

![image](https://user-images.githubusercontent.com/62879582/109294492-2b450a00-7825-11eb-9169-16e593b46cea.png)

- This is happening in: prod
- This requires a hotfix to production: yes 

### Steps to replicate
- Upload above model file
- Watch for toast notification shortly after upload complete
- Try the same file exported via Synchro Link (MO_SPM from Synchro Link.spm)
- It works

### Expected Behaviour
- Both files should upload

**Comment by carmenfan** [comment]
The file in question is v6.3, which we can't read without getting hands on Synchro Link v6.3

So throwing `Unsupported File Version` here is technically correct. The real fix can only happen when we get an upgrade

**Comment by carmenfan** [comment]
reviving this issue to code in 6.3 support
