### ISSUE TITLE
Include Revit Element ID in object's metadata

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepobouncer#440]
### Description

Currently, Revit models imported to 3D Repo via Plugin or Direct upload do not include **element IDs** (similar to IFC GUIDs). This leads to real issues when performing model data checks via API using tools like Power BI. This is going to create a number of problems for projects wanting to utilise Revit Models & Power BI for data validation.

_For example, **Wall** is a single model element that is converted into **3 meshes** in 3D Repo. I can only use those **mesh IDs** to count totals which results in the wrong count. If there were Unique **Element IDs**, then I would use those and get the correct amount of walls in my project._ 

### Goals

- [ ] Include Revit Element ID in the BIM Data

### Related Resources
Model in 3D Repo : [`Architecture`](https://www.3drepo.io/viewer/Bogdan_D/a2b6bf80-7bfd-11eb-866f-9178b76b7801)
Revit File: [`Architecture Revit 2020`](https://www.dropbox.com/preview/3D%20Repo%20Team%20Folder/3D%20Models/Element%20ID/School.rvt)

**Model in 3D Repo** (both via Plugin Upload & Direct Upload)
Family Name: **Basic Wall** Object count: **316 Objects**
![image](https://user-images.githubusercontent.com/19904513/109796505-24950900-7c10-11eb-9e57-67b568a098fa.png)

Model in Revit
Family Name: **Basic Wall** Object Count: **138 Instances**
![image](https://user-images.githubusercontent.com/19904513/109797236-198ea880-7c11-11eb-8e51-30fc40bb96c7.png)

**Revit Plugin** currently exports and includes Family Type ID in the BIM Card, but that's the same ID for multiple instances

![image](https://user-images.githubusercontent.com/19904513/109797522-8013c680-7c11-11eb-9d83-1415cf7e7318.png)

**Data in Power BI** is incorrect as the only number count parameter I can use is the **_id**
![image](https://user-images.githubusercontent.com/19904513/109798275-78a0ed00-7c12-11eb-9f8e-36ef6155c3c7.png)

**Comment by carmenfan** [comment]
@BDavydov

Just wanted to clarify this, as reading your issue and what you're referencing makes this a little ambiguous:

> For example, Wall is a single model element that is converted into 3 meshes in 3D Repo. I can only use those mesh IDs to count totals which results in the wrong count. If there were Unique Element IDs, then I would use those and get the correct amount of walls in my project.

All this change would do is add element id as part of the BIM metadata. It will not magically start returning you  element ids on group queries like we do with ifc guids. you could however achieve what you described here with counting the number of metadata records returned by [querying the metadata with rules](https://3drepo.github.io/3drepo.io/#api-Meta-queryMetadataByRules)

If you want element ids to function like ifc guids then that is a different feature and that would be a 3drepo.io work

**Comment by BDavydov** [comment]
@carmenfan atm groups count mesh IDs, so the numbers can be wrong relative to the element GUIDs. I understand that Element IDs in Revit are like IFC GUIDs, sadly we don't use them to give object counts in groups. I guess a feature where you can choose what to use to count objects would be best, but it's a whole scope of work

**Comment by carmenfan** [comment]
> @carmenfan atm groups count mesh IDs, so the numbers can be wrong relative to the element GUIDs. I understand that Element IDs in Revit are like IFC GUIDs, sadly we don't use them to give object counts in groups. I guess a feature where you can choose what to use to count objects would be best, but it's a whole scope of work

@BDavydov Yes I know what you're saying. And what I'm saying is the following:

1. this feature isn't going to change how groups work. you are still going to get mesh Ids when you do a smart group. So without further work the problem you illustrated will persist.
2. The example of you gave (e.g. trying to find out the amount of Basic Walls) - you could've counted the amount of objects by counting the number of metadata entries that satisfies the rule, and that should give you the number you wanted.
