### ISSUE TITLE
Units of Measure should be added to parameter name instead of value

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepobouncer#448]
### Description

Currently IFC and Plugin uploads handle Units of Measure differently, in order to utilise Smart Groups any measurement should be stored as a number, which means we need to find an alternative location for the Unit of Measure

### Goals

- [ ] Correct IFC units import - at the moment there are no units of measure carried over from the IFC file. This should change so the UoM is included in the parameter name:

![image](https://user-images.githubusercontent.com/62879582/111358688-8890e600-8682-11eb-99fe-22b730731b98.png)

- [ ] Move plugin Units of Measure from the value to the parameter and store the value as a number:

![image](https://user-images.githubusercontent.com/62879582/111359115-0523c480-8683-11eb-8161-a7c259e59113.png)

**Comment by carmenfan** [comment]
added a issue in https://github.com/3drepo/3drepoPlugin/issues/242 as well for this, as metadata labels are depicted by .bim for anything that comes in via the plugin

**Comment by carmenfan** [comment]
thought there's a separate issue on the unicode thing but there isn't....

the unicode symbols are escaped in the JSON, 3drepobouncer doesn't understand how to interpret it thus it's coming out with bad encoding on the 3drepo.io side. We should look into addressing this here as well.

**Comment by mosment3DRepo** [comment]
@carmenfan can we close this one too?

**Comment by carmenfan** [comment]
yep, this is done as part of #447 for the IFC units.
