### ISSUE TITLE
Update model LOD settings for DGN & RVT imports and potentially expose it to our users

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepobouncer#472]
### Description

Currently, we are having issues processing curved geometry for DGN and RVT models uploaded directly on the 3drepo.io website. The main issue is that circular or any geometry with smooth curves appears to be very faceted. resulting in poor geometric representation, causing false geometry interferences, unusable 3D Diff / Instant Clash features and most importantly general model appearance.

### Goals

- [ ] Change the current default setting to generate smoother geometry
- [ ] Expose settings to our users for choosing model LOD before processing.

### Related Resources

**How models look in 3D Repo**
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/19904513/121377934-a943a180-c93a-11eb-975c-170fda919d70.png)

**How these models are expected to look (_based on the design authoring tools_)**

![MicrosoftTeams-image](https://user-images.githubusercontent.com/19904513/121377940-a9dc3800-c93a-11eb-9d7e-8a90f8bc8031.png)

**Comment by carmenfan** [comment]
@BDavydov  can you provide some files with the issue

@mosment3DRepo  if there's any sense of urgency for this it needs to go into the roadmap, this isn't really a bug or quick enhancement - so realistically we won't be touching this issue unless it's in the roadmap:
1. we'd need some time to investigate the API to see what we can do and how we can do it to get what we want across various size/complexity of models
2. should it be possible to provide multiple levels of LoD , we then need to do some scoping on how this should be relay to the user and then figure out how this parameter should be passed down all the way from web UI to bouncer

**Comment by carmenfan** [comment]
closing in favour of #632
