### ISSUE TITLE
Remove processing of 2D lines in Revit upload

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepobouncer#477]
### Description

Currently a Revit file with a wireframe or detailed 3D View will have 2D lines processed by the bouncer and created as separate elements. This means models get duplicate elements for everything, one for the object and one for the wireframe

### Goals

- [ ] Prevent lines from being processed automatically

### Related Resources
![Revit lines](https://user-images.githubusercontent.com/62879582/124490124-a73df880-dda9-11eb-8147-eb91b42a33f4.gif)

**Comment by carmenfan** [comment]
@mosment3DRepo  you sure you want it removed?

I'm pretty sure we could make it so it's grouped under the same object.

**Comment by carmenfan** [comment]
Also if we do something like "ignore lines if there's triangles in this object", we would end up with the danger of missing something that needs to be there. i.e. if someone purposefully created a object that should have both lines and geometry.

p.s. also good if you can provide a file (I'm guessing this is the clinic model but still 😆

**Comment by mosment3DRepo** [comment]
> @mosment3DRepo you sure you want it removed?
> 
> I'm pretty sure we could make it so it's grouped under the same object.

After discussion, this is the ideal solution for now as it will resolve the current issues without a risk of missing geometry

**Comment by carmenfan** [comment]
done in #440
