### ISSUE TITLE
BIM data containing number values don't work with Smart Groups if there is an (SI) symbol

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepobouncer#492]
### Description

When I upload a Revit file on 3drepo.io the BIM Data that contains (SI) symbol won't work with smart groups. 

Here is an example:

Parameter **Area** Value **74 m2**

Here is an example for the same model uploaded using our plugin:
Parameter **Area (m2)** Value **74**

### Goals

- [ ] Make Parameters consistent across Revit versions
- [ ] Make Native Revit file BIM Data compatible with Smart Groups

### Related Resources

BIM Data for native file uploads:
![image](https://user-images.githubusercontent.com/19904513/129895253-24fe0f85-1b65-4d30-a19f-11d29fbb6713.png)

BIM Data for plugin uploads:
![image](https://user-images.githubusercontent.com/19904513/129895287-1c07c1eb-a5ec-466c-b36b-ab0753c0fc4b.png)

**Comment by mosment3DRepo** [comment]
@carmenfan do the values come through as 2 separate fields that we are concatenating, or is it one text string out of ODA?

**Comment by carmenfan** [comment]
@mosment3DRepo we're concatenating it, but I don't see a reason why it
shouldn't work, let me look into it first maybe it's just unicode being
escaped or something

**Comment by carmenfan** [comment]
Closing this, we've since moved units to the label instead of the data field #448
