### ISSUE TITLE
Better Control for Surface Pattern lines 

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepobouncer#494]
### Description

When I upload a Revit file to 3drepo.io it generates surface pattern lines. This is not what I was expecting to see, given that I have explicitly turned off the edge lines in my 3D View in Revit. Ensure that the surface lines are not generated if they're switched off in the 3D Views in Revit or allow to control their visibility in 3D Repo ie. toggle On/Off
These surface lines sometimes cause undesirable fuzzy effects.

### Goals

- [ ] Adhere to the 3D View setup in Revit
- [ ] Enable Surface/Edge Line toggle in 3D Repo (optional)

### Related Resources
sample model: https://github.com/3drepo/3drepobouncer/issues/494#issuecomment-901076417

**View in Revit:**
No Edge Lines (no surface Lines)
![image](https://user-images.githubusercontent.com/19904513/129895979-eed48f87-a6e2-4a78-9a84-6fdf32a62163.png)

Model in 3D Repo:
![Surface Lines](https://user-images.githubusercontent.com/19904513/129896383-7d44d449-c212-4a2d-9f37-e6cfcae758ea.gif)

**View in Revit when I deliberately turn on the Edge Lines:**
![image](https://user-images.githubusercontent.com/19904513/129896636-5df38875-8053-48e8-a0f7-a4610fdc688d.png)

**Comment by carmenfan** [comment]
@BDavydov would be good if you provide a sample file so we don't have to spend time trying to make something up

**Comment by BDavydov** [comment]
@carmenfan Here is a sample model (Revit 2021):
[Walls.zip](https://github.com/3drepo/3drepobouncer/files/7007200/Walls.zip)

**Comment by carmenfan** [comment]
I don't know how doable this is - we just get given what ODA spits out after selecting the views. we wouldn't know the difference between a edge line or a valid 2D geometry.

Will take some investigation time to even know if it's feasible.

**Comment by carmenfan** [comment]
Closing as it doesn't seem to be worth our time
