### ISSUE TITLE
SPM potentially clogging up the bouncer

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepobouncer#496]
### Description

The bouncer on prod and staging has experienced a traffic jam after certain models have been uploaded. It may be a coincidence, but it seems as thought the models in [this folder](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Clients/Prospects/Heijmans/Heijmans%20Models) are causing the issue

- This is happening in: both 
- This requires a hotfix to production: yes 

### Steps to replicate
- Make sure the bouncer queue is empty
- Upload the SPM files from the dropbox folder (all of them if possible)
- Wait > 3 hours, the models are still processing

**Comment by carmenfan** [comment]
@mosment3DRepo it's pretty much impossible for the process to run more than 3 hours because we[ execute a kill command with a 3 hour timeout ](https://github.com/3drepo/3drepobouncer/blob/master/tools/bouncer_worker/src/lib/runCommand.js#L38). I think we've established that the problem was unity licensing once again.

Is there anything that needs doing for this issue?

**Comment by mosment3DRepo** [comment]
Ok, I'm going to believe you for now.... 

@miadibe is going to try removing some geometry from the models once the staging backlog is cleared up, but we might need you to take a look at the file of it's still not working as there's nothing obviously bloating it in Synchro

**Comment by carmenfan** [comment]
there's 2 problems going on
- These spms has nodes that are really connected, and accessing parent array within the node is taking a lot of time (we do this a lot on checking integrity of the scene, and optimising the scene.
- The timeout isn't working for some reason... It's going into the timeout function, but it's not killing the process.

**Comment by carmenfan** [comment]
fixing the timeout in this function. optimising for the model to load is going into #497
