### ISSUE TITLE
FBX rotated on axis

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepobouncer#515]
### Description

FBX's seem to be coming in on rotated axis compared to previous behaviour

- This is happening in: staging 
- This requires a hotfix to production: ideally fixed in 4.19.3

Here is a link to a model file:
https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Models?preview=LOD300_London+(1).fbx

| Production | Staging | 
| --------------- | --------------- | 
| https://www.3drepo.io/viewer/PlanBase/353a00c0-9918-11ea-bb8a-7339f221efad/v5 | https://staging.dev.3drepo.io/viewer/PlanbaseTesting/ee465a60-382b-11ec-853f-3b7ea4edc886/lod_300_london_1 | 
| ![image](https://user-images.githubusercontent.com/62879582/139847026-f23cba88-4582-4879-91d1-092f902a70ba.png) | ![image](https://user-images.githubusercontent.com/62879582/139847065-e02a2d48-2cc4-4293-9b71-2229ae995ee3.png) | 

Edit by CF: See comments here https://github.com/3drepo/3drepobouncer/issues/515#issuecomment-1849993395

### Current Behaviour
- FBX files are not acknowledging the same Z as before

### Expected Behaviour
- FBX models should understand their rotation and render accordingly

**Comment by keifgwinn** [comment]
Also happening with this model https://www.dropbox.com/s/q8zh5fjkdh5u0g6/Demo%20Model%203.fbx?dl=0

**Comment by carmenfan** [comment]
With https://github.com/3drepo/3drepobouncer/pull/489/files, we have implemented the detection of orientation on fbx files, so this should orientate itself properly.

Either there is a bug in our code, or the file was exported incorrectly (e.g. it's saying Z up on the header but the data is Y up). we need to verify this.

**Comment by keifgwinn** [comment]
I ran into this the other day as well with
