### ISSUE TITLE
Users are struggling to federate models

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepobouncer#534]
### Description

If users receive a Revit file where the 3D View has edge lines turned on, we'll generate those lines. Unfortunately, it's an additional geometry added to our web viewer. Models with no edge lines will be far lighter. Those that have edge lines will consume a lot more Unity memory and so users won't be able to federate models.

Advised Revit 3D View setup:
https://help.3drepo.io/en/articles/4784899-prepare-and-upload-a-revit-file#model-set-up
Not everyone has a Revit license to do this. in 90% of cases 3D Views are set to hidden line + edge lines.

### Goals

- [ ] Allow users to have an option Include/Exclude the edge lines

### Related Resources

[Link to a model in 3D Repo](www.3drepo.io/viewer/Bogdan_D/91863230-632a-11ec-9862-6d9bcec75684)

[Link to sample Revit files](https://www.dropbox.com/sh/vv2324duud5ivly/AAA0UOMernLTeM_KDXLaq3ZHa?dl=0)

Model without the edge lines in Revit 3D View is only using **136MB of Unity memory**
![Model - No Lines](https://user-images.githubusercontent.com/19904513/147110044-a0124188-699a-46f5-a616-2af059d1eea1.jpg)

A model with the 3D View in Revit that includes edge lines consumes **231MB of Unity memory!!!**
![Model - With Lines](https://user-images.githubusercontent.com/19904513/147110058-086b6f2f-cb97-4bee-a9b1-14004f5c5fea.jpg)

**Comment by carmenfan** [comment]
as discussed before, it's not a pick and choose situation regarding edge lines, we either don't import 2D lines completely (which may mean we miss out contextual information, esp. when the LOD is low and revit convert objects to lines) or we take them all in.

We could potentially figure out if the 2D lines belong to the same object as another mesh that is 3D and in which case ignore them. but this may, again, be error prone if there are situations where there are legit 2D lines within a 3D geometry.

**Comment by mosment3DRepo** [comment]
@carmenfan could we include a checkbox similar to spm to exclude lines? We could set it off by default

**Comment by carmenfan** [comment]
It's possible yes
