### ISSUE TITLE
Have the test project link to the bouncer dll, rather that recompiling the bouncer source code  

### ISSUE THREAD

**Issue by har00n-haider** [3drepo/3drepobouncer#535]
### Description

Advantages to gain by doing this:
- Quicker compilation of the overall solution, only have to compile the test code for bouncer test project
- Reduce dependencies on libs/bouncer compilation considerations (preprocessor configurations etc.)
- You are testing exactly what the end user gets

**Comment by carmenfan** [comment]
that's not really feasible when you're doing unit tests requiring functions that aren't exposed by the dll. At least on windows.
