### ISSUE TITLE
Authentication failure under replicaset conditions

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepobouncer#548]
### Description

When you have authentication errors and are using a replicaset based configuration, the error message is not clear that is the cause.

- This is happening in: staging  
- This requires a hotfix to production: no 

### Steps to replicate
- Configure a replicaset configuration
- have a bad user/password combination

`{"label":"INIT","level":"verbose","message":"\t[STDERR]: terminate called after throwing an instance of 'boost::wrapexcept<boost::lock_error>'\n  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument\n","timestamp":"2022-02-15T10:08:52.880Z"}`

### Current Behaviour

`{"label":"INIT","level":"verbose","message":"\t[STDERR]: terminate called after throwing an instance of 'boost::wrapexcept<boost::lock_error>'\n  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument\n","timestamp":"2022-02-15T10:08:52.880Z"}`

### Expected Behaviour
`{"label":"INIT","level":"verbose","message":"\t[STDOUT]: [15-02-2022 10:11:05][INFO]: 3D Repo Bouncer Version: 4.21_0\n[15-02-2022 10:11:05][INFO]: Operation: test\n[15-02-2022 10:11:05][ERROR]: Error establishing Mongo Handler: Authentication failed.\n[15-02-2022 10:11:05][ERROR]: Failed to authenticate to the database: Authentication failed.\n","timestamp":"2022-02-15T10:11:05.723Z"}`

**Comment by sebjf** [comment]
Closed as completed; the new error handling in #707 displays mongo exceptions as nested exceptions in the log, so if the authentication failure mode is available, it will now be shown.
