### ISSUE TITLE
SPM colours not matching Synchro

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepobouncer#582]
### Description

Overlapping tasks in Synchro seem to be creating an issue in 3D Repo and it is unclear whether this is an issue with ynchro writing the SPM or 3D Repo interpreting the SPM.

The video below shows a sequence playing back in Synchro, the first task is set to turn the tree yellow, with the second turning it pink. As soon as the second task begins, Synchro adopts the pink override and ignores the initial tasks yellow override and continues until the second task is complete when the tree adopts its original green colour.

https://user-images.githubusercontent.com/62879582/172611954-aaa1b57a-6861-42d8-aa53-4567065b5aca.mp4

In 3D Repo the tress turns yellow, then pink at the correct times, but once the first task is complete the tree disappears, rather than remaining purple until the second task is complete. The tree then returns at the end when both tasks are finished.

https://user-images.githubusercontent.com/62879582/172646355-9cbaf0a5-32bd-40ff-8661-9f8fb570a357.mp4

Date | Activity | Synchro | 3DRepo
-- | -- | -- | --
28/02/2022 | Task 1 (Tree Install) starts | ![image](https://user-images.githubusercontent.com/62879582/172649794-b677db70-181c-45a1-9c06-2fe05371fa64.png) | ![image](https://user-images.githubusercontent.com/62879582/172649884-1ce35a17-8fe0-43c6-a0dd-794bcbb1db0a.png)
25/05/2022 | Task 2 (Tree Maintain) starts |  ![image](https://user-images.githubusercontent.com/62879582/172649959-f081ad0e-4b4c-48db-bab3-894dfd70ce4b.png) | ![image](https://user-images.githubusercontent.com/62879582/172653749-3da568b7-2c05-43ff-b908-5e91b1adb457.png)
19/07/2022 | Task 1 (Tree Install) ends | ![image](https://user-images.githubusercontent.com/62879582/172649959-f081ad0e-4b4c-48db-bab3-894dfd70ce4b.png) | ![image](https://user-images.githubusercontent.com/62879582/172653792-8ab6ba80-0aed-482c-9eed-f03ef2181fe7.png)
12/09/2022 | Task 2 (Tree Maintain) ends | ![image](https://user-images.githubusercontent.com/62879582/172650274-e17b1e6f-f6bb-4625-8a6b-c549f37f695a.png) | ![image](https://user-images.githubusercontent.com/62879582/172653817-52d4965f-6e2f-4534-a433-2e66b570ae32.png)

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Open this model: [Tree Install](https://www.3drepo.io/viewer/mosment3d/0b561d20-e722-11ec-af14-254561b0a74f)
- Playback sequence and compare to Synchro

### Current Behaviour
- Users seeing different colour/visibility overrides in Synchro vs 3D Repo

### Expected Behaviour
- Model should highlight the same as Synchro

### Pictures/ Gifs of the error

Files available https://www.dropbox.com/sh/3dua78tgs20cln0/AAB-UKIGLmZpetsCTZEAqZHoa?dl=0

Link to model: https://www.3drepo.io/viewer/mosment3d/8fc7c970-e739-11ec-bb02-fdc66ef39f30

**Comment by carmenfan** [comment]
This is actually a fault from synchro API.

Synchro API gives us the animation, completely separate from the tasks. and the animation timeline tells us at each point in time, what the colours/opacity/transform values are for each resource group.

It doesn't actually tell us what tasks drives which action. We just get the whole situation at a certain timeframe, so this is not a piece of information we have.

**Comment by carmenfan** [comment]
Closing as it is impossible to fix.
