### ISSUE TITLE
Refactor RepoProjectSettings

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepobouncer#60]
Refactor RepoProjectSettings bson and add new properties as follows:
{
    "_id" : "103DBD12_fed",
    "owner" : "richard",
    "type" : "architectural",
    "permissions" : [ 
        7, 
        0, 
        0
    ],
    "properties" : {
        "pinSize" : 1.6000000000000001,
        "avatarHeight": 1.6,
        "visibilityLimit": 1000.0,
        "speed": 5.0,
        "zFar": 1000.0,
        "zNear": 0.001
    }
}

**Comment by carmenfan** [comment]
````c++
/**
	* Make a copy of this role and add the specified access rights into
	* the new role
	* NOTE1: this function does NOT alter the existing RepoRole
	* NOTE2: if the role already has privilege on the project in question
	*       the privileges will be overwritten!
	* @param permissions new permissions to add
	*/
	RepoRole cloneAndAddPermissions(
		const std::vector<RepoPermission> &permissions
		);


	/**
	* Make a copy of this role and add the specified privileges into
	* the new role
	* NOTE1: this function does NOT alter the existing RepoRole
	* NOTE2: if the role already has privilege on the project in question
	*       the privileges will be overwritten!
	* @param privileges new privileges to add
	*/
	RepoRole cloneAndAddPrivileges(
		const std::vector<RepoPrivilege> &privileges
		);

````

**Comment by carmenfan** [comment]
Now changed to this:

````c++
	/**
	* Make a copy of this role and add the update access rights into
	* the new role
	* NOTE1: this function does NOT alter the existing RepoRole
	* NOTE2: if the role already has privilege on the project in question
	*       the privileges will be overwritten!
	* NOTE3: Access rights that used to exist but not specified in this
	*        list will be removed
	* @param permissions new permissions list
	*/
	RepoRole cloneAndUpdatePermissions(
		const std::vector<RepoPermission> &permissions
		);
````

**Comment by jozefdobos** [comment]
What I need is to copy over (append) from existing role privileges and inherited roles into a newly created role.

**Comment by carmenfan** [comment]
I don't get it, the clone and Update should do what you need from what we discussed.

You don't want to append because you want to remove the ones that no longer exists. So what you want to do essentially is create a new list of privileges that is generated from AccessRights and replace that with what was the list of privileges generated from the old AccessRights, whilst remaining the non project access rights related privileges and inherited roles, which is exactly what that function is doing.

**Comment by jozefdobos** [comment]
The problem is arising from the name changes of the role in the dialog. So essentially I'm always creating a new role just in case. The current cloneAndUpdate works fine, but what I do is create new role and clone it in order to add old permissions (the other way round than what originally envisioned). All I need to add is copy over the inherited roles and I reckon it would work just fine (in theory).

**Comment by carmenfan** [comment]
why would you do it that way? there's nothing to preserve on the new role if you have just created it. What you want is probably to cloneAndUpdate and either 1. have a setName() function to once again clone and set name, or 2. create that new role base on the old role's privileges (after cloneAndUpdate). I would probably go for option num. 2 as I think that's what the User bson is doing on a user dialogue

Now it goes into question as to should you be disabling the ability to change the name if the person is editing the role. It doesn't work as the user's intention of changing the role name as you're adding a new role but not removing the old one, and like usernames, i wouldn't have thought you should be able to do that.

**Comment by jozefdobos** [comment]
Ok, I have coded in option 2. It sort of works apart from not copying over privileges when cloning nodeUserRole (inherited roles are copied fine). See the new function in factory.

Re not changing the name on edit, that is there already but I still let the user to override it with a tickbox for convenience.
