### ISSUE TITLE
Process should not exit as if it has completed successfully if it failed to write a file to fs

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#606]
### Description
We are running into situations where the process failed to save a file to fs after retries, gave up and the process returns error code 0.

### Steps to replicate
force a fs file to fail

### Current Behaviour
process is returning error code 0

### Expected Behaviour
process should return the correct error code (probably 4)

### Pictures/ Gifs of the error
<img width="1204" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/11945337/222504051-8809b314-fa83-43ff-bda4-2f3c2bd36736.png">

**Comment by sebjf** [comment]
Closing as completed.

Three different error modes (folder is read-only, failed is forced true, and the condition for failed prompting a retry is forced true) have been tried, and all modes return 4 or 32, so this has been fixed during previous refactors.
