### ISSUE TITLE
Provide better reasoning in the log for failures to write to file system

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepobouncer#608]
### Description

We're seeing a lot more failed to write to filesystem since v5, with a fixed retry of only a few seconds. However, I've noticed this across all the environments we're running in now, local, AWS efs, on premise NAS, and so I suspect there might be something else happening than actually something stopping the writes to disk.

I realise this needs more investigation, but I'm opening this ticket to look into it so I don't forget to mention it.

I've seen this behaviour in prod, on staging, and on local.

It would be good to be able to make this timeout/retry configurable to aid in investigations, and also treat FS write failures as soft fails worthy of returning to the queue.

- This is happening in: both 
- This requires a hotfix to production: yes/no 

Edit by CF: this is where we're writing the file. We need to investigate if we can catch the error better and find out the reason and dump it into the logs https://github.com/3drepo/3drepobouncer/blob/master/bouncer/src/repo/core/handler/fileservice/repo_file_handler_fs.cpp#L138

### Steps to replicate
- TBD

### Current Behaviour
- Occasional file system errors that don't appear to be file system related as every time I've tested immediately on it it's been able to write.

### Expected Behaviour
- no errors

**Comment by carmenfan** [comment]
> It would be good to be able to make this timeout/retry configurable to aid in investigations, and also treat FS write failures as soft fails worthy of returning to the queue.

This part is gonna be quite involved since we'd have a corrupted revision in the database (since fs writes would def be at the stage where we've written a fair amount of bson documents. With a dedicated revId we'd be trying to do the same inserts as before

**Comment by carmenfan** [comment]
What we probably could (and should do) is dump the reasoning on the log

**Comment by carmenfan** [comment]
@sbanethia did some investigation and could not found a reliable way to get any meaningful reasoning out of the failure.

So there is no point doing this issue. closing.
