### ISSUE TITLE
Add ability to retrieve RepoRoleSettings one by one from DB

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepobouncer#61]
Add body to the following function in controller so that RoleSettings can be retrieved as findOne from the DB given uniqueRoleName in place of ID field from settings.roles collection.

repo::core::model::RepoRoleSettings getRoleSettings(
            const RepoToken *token,
            const std::string &database,
            const std::string &uniqueRoleName
            )

See also issue #60

**Comment by carmenfan** [comment]
This is done on branch ISSUE_61 (with ISSUE_60's changes merged onto 61). I did a quick test it seems to be ok, give it a test and close this if it works as you want it.

**Comment by jozefdobos** [comment]
Works as advertised, merged into #60  Thanks!
