### ISSUE TITLE
Bouncer to dump version number on init

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepobouncer#635]
### Description

Print out bouncer version number when bouncer starts

### Tasks

- [ ] Print out version number

**Comment by Charence** [comment]
Can we have it displayed on frontend too?

**Comment by carmenfan** [comment]
@Charence  by front end do you mean 3drepo.io?

**Comment by carmenfan** [comment]
> > @Charence by front end do you mean 3drepo.io?
> 
> Yes, on 3drepo.io frontend. At the moment it'll say the io version at the bottom, could it also say the bouncer version. Ali and I were discussing it.

Better if it doesn't, it's not going to be easy to guarantee it's up to date.

**Comment by sebjf** [comment]
Closing as completed because bouncer has done this for a while.
