### ISSUE TITLE
Turn off IFC 2D

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#661]
### Description
As requested by @AsiteZane, we're turning off IFC polyline support for now until there is a better understanding of exactly what the users want to see.

At the moment we're porting everything including IFC Annotations, but we need to identify what they want to see and what they don't want to see, and how does that translates into IFC Types and filter out the ones they don't want (or provide options on the UI so the users can select)

### Goals
- [ ] don't read in polylines

**Comment by AsiteZane** [comment]
Does this also apply for annotations coming in through RVT files? I think that was a particular problem on Aldar when it was bringing in the grid lines and bounding boxes

**Comment by carmenfan** [comment]
> Does this also apply for annotations coming in through RVT files? I think that was a particular problem on Aldar when it was bringing in the grid lines and bounding boxes

 No, this is exclusively IFC related. RVT (native) would be more complicated as we get what ODA gives us.

**Comment by carmenfan** [comment]
> @AsiteZane No, this is exclusively IFC related. RVT (native) would be more complicated as we get what ODA gives us.

@AsiteZane  sorry just to give clarity, on RVT we can still just completely ignore 2D lines - which is what we're doing with IFC at the moment.

The problem we will face is that when the user adjust the LoD on revit to really low, sometimes 3D objects turns into 2D lines. so if we ignore 2D lines all together,, we risk the situation where we don't bring in geometry that would be expected to be there. Of course we can remedy that with looking at metadata just like what we want to do in IFC in the future.

**Comment by AsiteZane** [comment]
@carmenfan - apologies, i was bleeding another problem into this ticket, probably should have just asked on teams. Thank you for the explanation :)
