### ISSUE TITLE
Porting SRC file generation from Repo io

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#67]
porting the src file generation from repo.io to 3drepobouncer. so it is done at the point of import

@timscully1983 Is this still the plan?

**Comment by timscully1983** [comment]
I think this should be implemented as part of the Streaming project, due to the required conversion to glTF.

**Comment by carmenfan** [comment]
SRC Generation is done and working as far as i can tell.

see #76 for x3d and json generation

**Comment by carmenfan** [comment]
opening for bug fixing on massive mesh that needs to be split

**Comment by carmenfan** [comment]
meshSplit should now work. Also fixed a bug with cameras
