### ISSUE TITLE
Add a flag to indicate upload progress in the revision node

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#72]
As uploads can take a significant amount of time/it may fail, a flag in the revision node to indicate if the model has finished uploading can be useful

**Comment by jozefdobos** [comment]
I'd actually do it the Windows way: Save the first entry as UNFINISHED and as the last step remove it. If not removed, upload has failed. (This is how Windows does it to tell you the system has not shut down correctly on the next bootup).

@timscully1983 what do you think?

**Comment by carmenfan** [comment]
That's effectively what it is, The revision node is the first node that gets commited and that's the node that will get updated once it's done. The flag is basically there to show it's unfinished

**Comment by carmenfan** [comment]
Also useful for the c++ to be able to revert the commit if it failed

**Comment by carmenfan** [comment]
During Commit:
![image](https://cloud.githubusercontent.com/assets/11945337/12581754/95a87f3e-c430-11e5-8dc8-b0c29c2dc99c.png)

After Commit
![image](https://cloud.githubusercontent.com/assets/11945337/12581902/958ab624-c431-11e5-97af-34d0b958c2ff.png)

**Comment by carmenfan** [comment]
Reverting a commit is technically broader than the flag and deserve it's own issue, so that issue is being branched out to #80

**Comment by carmenfan** [comment]
@timscully1983 This is done and merged into master. Be careful that src generation (not x3d yet) is also merged in so anything you import with this branch/master of current time will also generate a SRC for you.

This is great for me as it'll put the SRC generation against as many tests as possible, but if the model doesn't load, you might want to clear the stash before trying again. 

alternatively, you can disable it in repo_manipulator.cpp:178:

````c++
void RepoManipulator::commitScene(
	const std::string                             &databaseAd,
	const repo::core::model::RepoBSON 	  *cred,
	repo::core::model::RepoScene           *scene,
	const std::string                      &owner)
{
	repo::core::handler::AbstractDatabaseHandler* handler =
		repo::core::handler::MongoDatabaseHandler::getHandler(databaseAd);

	std::string msg;
	if (handler && scene && scene->commit(handler, msg, owner.empty() ? cred->getStringField("user") : owner))
	{
		repoInfo << "Scene successfully committed to the database";
		if (scene->commitStash(handler, msg))
		{
			repoInfo << "Commited scene stash successfully.";

			repoInfo << "Generating SRC encoding for web viewing...";
			if (generateAndCommitSRCBuffer(databaseAd, cred, scene))
			{
				repoInfo << "SRC file stored into the database";
			}
			
		}
		else
		{
			repoError << "Failed to commit scene stash : " << msg;
		}


	}
	else
	{
		repoError << "Error committing scene to the database : " << msg;
	}


}
````
