### ISSUE TITLE
Potential memory leak in repo_face_t

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#73]
repo_face_t, the intermediary struct to reduce the reliance of assimp within the library, has the following structure definition:

````c++
typedef struct{
	uint32_t numIndices;
	uint32_t *indices;
}repo_face_t;
````

I'm pretty certain the indices aren't freed after use at the moment. should either change it to std::vector or free accordingly.

**Comment by jozefdobos** [comment]
Go for a vector then (I'd just pass in &vec[0] as an array pointer job done)

**Comment by carmenfan** [comment]
the array has now been converted to std::<vector>. numIndices is now a redundant value as that's just the size of the vector, which we can get from size()... which means repo_face_t has little reason to exist as a struct... so repo_face_t is now

````c++
typedef std::vector<uint32_t> repo_face_t;
````
