### ISSUE TITLE
Bouncer crashes if the database connection is lost during operations

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepobouncer#92]
Reduce the chance of this happening by checking if the database connection is still running everytime before we use it

**Comment by jozefdobos** [comment]
wondering if the new driver is any better with this...

**Comment by carmenfan** [comment]
it could be that it throws a connection lost exception that i'm not catching.. needs looking into really.

**Comment by carmenfan** [comment]
fixed now.
